=== Ilvondir/bad-laboratories/Lab1/ex7.xsd
<?xml version="1.0"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">

    <!-- Venetian Blind -->

    <xs:complexType name="wagon">
        <xs:sequence>
            <xs:element name="numer" type="xs:integer"/>
            <xs:element name="rodzaj" type="xs:string"/>
        </xs:sequence>
    </xs:complexType> 

    <xs:complexType name="wagony">
        <xs:sequence>
            <xs:element name="wagon" type="wagon" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="przystanek">
        <xs:sequence>
            <xs:element name="nazwa" type="xs:string"/>
            <xs:element name="przyjazd" type="xs:time"/>
            <xs:element name="odjazd" type="xs:time"/>
        </xs:sequence>
    </xs:complexType>    

    <xs:complexType name="przystanki">
        <xs:sequence>
            <xs:element name="przystanek" type="przystanek" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="przewoznik">
        <xs:restriction base="xs:string">
            <xs:maxLength value="15"/> 
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="pociag">
        <xs:sequence>
            <xs:element name="nazwa" type="xs:string"/>
            <xs:element name="rodzaj" type="xs:string"/>
            <xs:element name="przewoznik" type="przewoznik"/>
            <xs:element name="przystanki" type="przystanki"/>
            <xs:element name="wagony" type="wagony"/>
        </xs:sequence>
        <xs:attribute name="numer" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="pociagi">
        <xs:sequence>
            <xs:element name="pociag" type="pociag" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rozklad">
        <xs:sequence>
            <xs:element name="pociagi" type="pociagi" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="od" type="xs:date"/>
        <xs:attribute name="do" type="xs:date"/>
    </xs:complexType>

    <xs:element name="rozklad" type="rozklad" />


</xs:schema>

=== Ilvondir/bad-laboratories/Lab1/rozklad.xml
<?xml version="1.0" encoding="UTF-8"?>

<rozklad od="2023-10-21" do="2023-11-12" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ex7.xsd">

    <pociagi>

        <pociag numer="1">
            <nazwa>Agata</nazwa>
            <rodzaj>ekspres</rodzaj>
            <przewoznik>Galicja EXPRESS</przewoznik>

            <przystanki>
                <przystanek>
                    <nazwa>Kopisto Rejtana</nazwa>
                    <przyjazd>11:31:00</przyjazd>
                    <odjazd>11:33:00</odjazd>
                </przystanek>
                <przystanek>
                    <nazwa>Kopisto</nazwa>
                    <przyjazd>11:44:00</przyjazd>
                    <odjazd>11:46:00</odjazd>
                </przystanek>
                <przystanek>
                    <nazwa>Podwisłocze</nazwa>
                    <przyjazd>11:58:00</przyjazd>
                    <odjazd>11:59:00</odjazd>
                </przystanek>
            </przystanki>

            <wagony>
                <wagon>
                    <numer>1</numer>
                    <rodzaj>wagon sypialny</rodzaj>
                </wagon>
                <wagon>
                    <numer>2</numer>
                    <rodzaj>wagon klasy 2</rodzaj>
                </wagon>
                <wagon>
                    <numer>3</numer>
                    <rodzaj>wagon klasy 1</rodzaj>
                </wagon>
            </wagony>
        </pociag>

        <pociag numer="2">
            <nazwa>Bursa</nazwa>
            <rodzaj>pospieszny</rodzaj>
            <przewoznik>Marcel</przewoznik>

            <przystanki>
                <przystanek>
                    <nazwa>Kwiatowe</nazwa>
                    <przyjazd>16:11:00</przyjazd>
                    <odjazd>16:12:00</odjazd>
                </przystanek>
                <przystanek>
                    <nazwa>Przyborowie</nazwa>
                    <przyjazd>16:21:00</przyjazd>
                    <odjazd>16:22:00</odjazd>
                </przystanek>
            </przystanki>

            <wagony>
                <wagon>
                    <numer>1</numer>
                    <rodzaj>wagon klasy 1</rodzaj>
                </wagon>
                <wagon>
                    <numer>2</numer>
                    <rodzaj>wagon restauracyjny</rodzaj>
                </wagon>
            </wagony>
        </pociag>

        <pociag numer="3">
            <nazwa>Agrowagon</nazwa>
            <rodzaj>pospieszny</rodzaj>
            <przewoznik>TransPan</przewoznik>

            <przystanki>
                <przystanek>
                    <nazwa>Moskwa</nazwa>
                    <przyjazd>11:25:00</przyjazd>
                    <odjazd>12:09:00</odjazd>
                </przystanek>
                <przystanek>
                    <nazwa>Mińsk</nazwa>
                    <przyjazd>17:42:00</przyjazd>
                    <odjazd>18:22:00</odjazd>
                </przystanek>
                <przystanek>
                    <nazwa>Warszawa</nazwa>
                    <przyjazd>23:58:00</przyjazd>
                    <odjazd>00:55:00</odjazd>
                </przystanek>
                <przystanek>
                    <nazwa>Berlin</nazwa>
                    <przyjazd>05:15:00</przyjazd>
                    <odjazd>06:18:00</odjazd>
                </przystanek>
            </przystanki>

            <wagony>
                <wagon>
                    <numer>1</numer>
                    <rodzaj>wagon klasy 1</rodzaj>
                </wagon>
                <wagon>
                    <numer>2</numer>
                    <rodzaj>wagon klasy 1</rodzaj>
                </wagon>
                <wagon>
                    <numer>3</numer>
                    <rodzaj>wagon klasy 1</rodzaj>
                </wagon>
                <wagon>
                    <numer>4</numer>
                    <rodzaj>wagon restauracyjny</rodzaj>
                </wagon>
                <wagon>
                    <numer>5</numer>
                    <rodzaj>wagon klasy 2</rodzaj>
                </wagon>
                <wagon>
                    <numer>6</numer>
                    <rodzaj>wagon klasy 2</rodzaj>
                </wagon>
                <wagon>
                    <numer>7</numer>
                    <rodzaj>wagon klasy 2</rodzaj>
                </wagon>
            </wagony>
        </pociag>

    </pociagi>

</rozklad>
